export const AUTH_CONSTANTS = {
    STUDENT_TYPES: {
        MEDICAL_STUDENT: "MEDICAL_STUDENT",
        NURSING_STUDENT: "NURSING_STUDENT",
        DENTAL_STUDENT: "DENTAL_STUDENT",
        PHARMACY_STUDENT: "PHARMACY_STUDENT",
        PUBLIC_HEALTH_STUDENT: "PUBLIC_HEALTH_STUDENT",
        DENTAL_HYGIENE_STUDENT: "DENTAL_HYGIENE_STUDENT",
        MEDICAL_LAB_TECHNOLOGY_STUDENT: "MEDICAL_LAB_TECHNOLOGY_STUDENT",
        RADIOLOGY_STUDENT: "RADIOLOGY_STUDENT",
        PHYSIOTHERAPY_STUDENT: "PHYSIOTHERAPY_STUDENT",
    },
};

